"""
Instagram Reels Downloader (gallery-dl + Cookie Mode)
=====================================================
Download all reels from an Instagram profile using gallery-dl.
gallery-dl is highly optimized for scraping and respects rate limits
better than Instaloader.

Usage:
  python instagram_reels_downloader.py --profile USERNAME --cookie "YOUR_SESSIONID"
  python instagram_reels_downloader.py --profile USERNAME --limit 10
"""

import os
import sys
import re
import argparse
import subprocess
from pathlib import Path


# Paths for saving cookie
COOKIE_TXT_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "instagram_cookies.txt")
COOKIE_RAW_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".ig_cookie.txt")

def extract_username(profile_input: str) -> str:
    profile_input = profile_input.strip().rstrip("/")
    profile_input = re.split(r"[?#]", profile_input)[0]
    profile_input = re.sub(r"/(reels|posts|tagged|saved|followers|following)/?$", "", profile_input)

    url_pattern = r"(?:https?://)?(?:www\.)?instagram\.com/([A-Za-z0-9_.]+)"
    match = re.match(url_pattern, profile_input)
    if match:
        return match.group(1)

    username = profile_input.lstrip("@")
    if re.match(r"^[A-Za-z0-9_.]+$", username):
        return username

    raise ValueError(f"Invalid username/URL: '{profile_input}'")

def save_raw_cookie(sessionid: str):
    """Save raw sessionid for memory."""
    with open(COOKIE_RAW_FILE, "w") as f:
        f.write(sessionid.strip())

def load_saved_cookie() -> str | None:
    if os.path.exists(COOKIE_RAW_FILE):
        with open(COOKIE_RAW_FILE, "r") as f:
            cookie = f.read().strip()
            if cookie:
                return cookie
    return None

def generate_netscape_cookie_file(sessionid: str):
    """
    Generate a Netscape formatted cookie file for gallery-dl.
    """
    sessionid = sessionid.strip()
    
    lines = [
        "# Netscape HTTP Cookie File",
        "# This file is automatically generated by instagram_reels_downloader.py",
        f".instagram.com\tTRUE\t/\tTRUE\t0\tsessionid\t{sessionid}"
    ]
    with open(COOKIE_TXT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  [✓] Format cookie gallery-dl di-generate: {COOKIE_TXT_FILE}")

def download_reels_gallerydl(
    target_username: str,
    output_dir: str = None,
    limit: int = None
):
    if output_dir is None:
        output_dir = os.path.join("instagram_reels", target_username)
    os.makedirs(output_dir, exist_ok=True)

    print()
    print("=" * 60)
    print(f"  Instagram Reels Downloader (gallery-dl)")
    print("=" * 60)
    print(f"  Target   : @{target_username}")
    print(f"  Output   : {os.path.abspath(output_dir)}")
    print(f"  Limit    : {limit or 'Semua reels'}")
    print("=" * 60)
    print()

    # URL to user's video tab (reels) or profile depending on what is accessible.
    # gallery-dl handles generic instagram profiles well, downloading videos
    target_url = f"https://www.instagram.com/{target_username}/reels/"
    
    cmd = [
        "gallery-dl",
        "--cookies", COOKIE_TXT_FILE,
        "--directory", output_dir,
        # Mengatur format output (Opsional: [shortcode].mp4)
        "--filename", "{shortcode}.{extension}",
        # Filter ke mp4 saja agar tidak ikut download Thumbnail jika tidak perlu
        "--filter", "extension == 'mp4'",
        # Opsi auto skip file yang sudah ada
        "--abort", "5",  # stop jika menemukan 5 file yang sudah ada (untuk update/sync)
    ]
    
    if limit:
        # Download rentang dari 1 sampai Limit
        cmd.extend(["--range", f"1-{limit}"])

    cmd.append(target_url)

    print("[*] Memulai proses download...")
    print("    Silakan tunggu, gallery-dl sedang mencari dan mengunduh video...\n")

    try:
        process = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding='utf-8',
            errors='replace'
        )

        downloaded_count = 0
        
        for line in process.stdout:
            line = line.strip()
            if not line:
                continue
                
            if line.startswith("#"):
                # Menampilkan log skip / aborted dll
                print(f"  {line}")
            elif line.endswith(".mp4"):
                # Baris ini menampilkan file output
                print(f"  ✅ Tersimpan: {os.path.basename(line)}")
                downloaded_count += 1
            else:
                print(f"  > {line}")

        process.wait()
        
        print()
        print("=" * 60)
        print("  ✅ SELESAI")
        print(f"  Download / Diproses: {downloaded_count} video")
        print("=" * 60)
        
    except FileNotFoundError:
        print("[!] ERROR: gallery-dl tidak ditemukan.")
        print("    Install dengan: pip install gallery-dl")
    except Exception as e:
        print(f"[!] Terjadi kesalahan: {e}")

def main():
    parser = argparse.ArgumentParser(description="Download Instagram Reels (gallery-dl).")
    parser.add_argument("--profile", "-p", type=str, help="Profile URL atau username target")
    parser.add_argument("--cookie", "-c", type=str, default=None, help="Sessionid cookie value")
    parser.add_argument("--new-cookie", action="store_true", help="Input cookie baru (replace yang lama)")
    parser.add_argument("--output", "-o", type=str, default=None, help="Folder output")
    parser.add_argument("--limit", "-l", type=int, default=None, help="Maks jumlah reels")

    args = parser.parse_args()

    # Get sessionid cookie
    sessionid = None

    if args.cookie:
        sessionid = args.cookie.strip().strip("\"'")
        save_raw_cookie(sessionid)
    elif args.new_cookie:
        sessionid = input("Paste sessionid cookie: ").strip().strip("\"'")
        save_raw_cookie(sessionid)
    else:
        sessionid = load_saved_cookie()
        if sessionid:
            masked = sessionid[:8] + "..." + sessionid[-4:]
            print(f"\n  [✓] Cookie tersimpan ditemukan: {masked}")
        else:
            sessionid = input("Paste sessionid cookie: ").strip().strip("\"'")
            save_raw_cookie(sessionid)
            
    if not sessionid:
        print("  [!] Cookie tidak valid. Keluar.")
        sys.exit(1)

    # Convert sessionid to netscape format cookies.txt
    generate_netscape_cookie_file(sessionid)

    profile_input = args.profile
    if not profile_input:
        profile_input = input("\n  Masukkan profile URL/username target: ").strip()
        if not profile_input:
            sys.exit(1)

    try:
        target = extract_username(profile_input)
    except ValueError as e:
        print(f"  [!] {e}")
        sys.exit(1)

    # Make sure gallery-dl is installed
    try:
        subprocess.run(["gallery-dl", "--version"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)
    except (subprocess.CalledProcessError, FileNotFoundError):
        print("\n  [!] Menginstall gallery-dl...")
        subprocess.run([sys.executable, "-m", "pip", "install", "-U", "gallery-dl"])

    download_reels_gallerydl(target, output_dir=args.output, limit=args.limit)


if __name__ == "__main__":
    main()
